---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: stroke
  namespace: default
spec:
  predictors:
  - name: model-clf
    traffic: 50
    componentSpecs:
    - spec:
        containers:
        - image: seldonio/clf:0.0.1
          imagePullPolicy: IfNotPresent
          name: classifier
          env:
          - name: SELDON_LOG_LEVEL
            value: INFO
          resources:
            requests:
              memory: 1Mi
          
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      name: classifier
      endpoint:
        type: REST
      type: MODEL
    replicas: 1
    annotations:
      predictor_version: v1

  - name: model-tree
    traffic: 50
    componentSpecs:
    - spec:
        containers:
        - image: seldonio/tree:0.0.1
          imagePullPolicy: IfNotPresent
          name: classifier
          env:
          - name: SELDON_LOG_LEVEL
            value: INFO
          resources:
            requests:
              memory: 1Mi
          
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      name: classifier
      endpoint:
        type: REST
      type: MODEL
    replicas: 1
    annotations:
      predictor_version: v1

